### ISSUE TITLE
ReferenceError: Unknown plugin "add-module-exports"

### ISSUE THREAD

**Issue by alozytskyi** [jake-daniels/redux-dynamix#1]

**Comment by jake-daniels** [comment]
@alozytskyi Could you please provide more information about this?

**Comment by alozytskyi** [comment]
@jake-daniels you should add prebuilt dist version or the project fails to build without `babel-plugin-add-module-exports`

**Comment by jake-daniels** [comment]
@alozytskyi I don't think it's a good idea to put build output to version control. I can build the module without any problems. `babel-plugin-add-module-exports` is in devDependencies.
