### ISSUE TITLE
Can 0.1.2 version be released to npm?

### ISSUE THREAD

**Issue by Azein** [jake-daniels/redux-dynamix#3]
You already fixed object rest/spread (which caused an issue in my CRA build process) in latest patch, are there anything that's holding you back from release? Maybe you need help with something?

**Comment by jake-daniels** [comment]
@Azein I already released that. I guess there was some error with the publish. I had to lift it up to 0.1.3 and release that. It should be working now, I installed that version with no problems.

**Comment by Azein** [comment]
Are you sure that newer versions actually arrived on npm? For me and some other people it's still 0.1.1

**Comment by jake-daniels** [comment]
@Azein  `npmjs.com` still shows version 0.1.1 (I'll contact support about that). But I have tried to install the package in a fresh repository just now and it worked. Version 0.1.3 was installed.

**Comment by Azein** [comment]
@jake-daniels doesn't work for me this way, sadly. Well, I hope that npm guys will resolve this, for now I'm sticking with node_modules manual patch.

**Comment by jake-daniels** [comment]
@Azein I tried it with colleague in work and he didn't manage to install the latest version. I'm waiting for reply from `npmjs.com`. I'm sorry for the trouble.

**Comment by jake-daniels** [comment]
@Azein There was some problem with credentials. I tried it now on 2 different computers. Seems to be solved now.

**Comment by Azein** [comment]
Yes, it's all ok now. Thanks for good work =)
