### ISSUE TITLE
Don't support Immutable

### ISSUE THREAD

**Issue by ystarlongzi** [jake-daniels/redux-dynamix#4]
Hi, the root state is [immutable](https://facebook.github.io/immutable-js/) in my project, and when i use `redux-dynamix`, it will throw error.

Then i review the source code, and find that  [index.js#L16-L33](https://github.com/jake-daniels/redux-dynamix/blob/master/index.js#L16-L33) don't support immutable.

Could you fix it?

**Comment by jake-daniels** [comment]
@ystarlongzi Sorry, I don't want to couple this tool with specific libraries, so I will keep it in pure JS. But feel free to fork it and update it to your needs.
